# Generated by Django 3.0.7 on 2020-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0002_auto_20200614_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('data_pub', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('exif_data', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
