# Generated by Django 3.0.7 on 2020-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0003_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='image2',
            name='photo',
            field=models.ImageField(upload_to='photos2'),
        ),
    ]
